### PR TITLE
Revert "Revert "Revert "Revert "Test PR""""

### PR DESCRIPTION
**Pull request by andesyudanto**
Reverts githumb/kodok#7

### CODE REVIEW

**Comment by andesyudanto** [comment]
:ok_hand:

**Comment by andesyudanto** [comment]
:ok_hand:

**Comment by andesyudanto** [comment]
:ok_hand:

**Comment by andesyudanto** [comment]
:ok_hand:

**Comment by andesyudanto** [comment]
#design

**Comment by gde-vt** [comment]
testtttttt

**Pull request closed without merging**
